export enum BillableCategory {
    STORAGE_FEE_BY_NET_VOLUME = 'STORAGE_FEE_BY_NET_VOLUME',
    STORAGE_FEE_BY_GROSS_VOLUME = 'STORAGE_FEE_BY_GROSS_VOLUME',
    STORAGE_FEE_BY_LOCATION_COUNT = 'STORAGE_FEE_BY_LOCATION_COUNT',
    STORAGE_FEE_BY_PALLET_COUNT = 'STORAGE_FEE_BY_PALLET_COUNT',
    STORAGE_FEE_BY_CASE_COUNT = 'STORAGE_FEE_BY_CASE_COUNT',
    /**
     * 
     * 
    HANDLING_FEE = 'HANDLING_FEE',
    ADDON_FEE = 'ADDON_FEE',
    TRANSACTIONS = 'TRANSACTIONS',
    RECEIPT_LINE_PROCESS_FEE = 'RECEIPT_LINE_PROCESS_FEE',
    RECEIPT_PROCESS_FEE = 'RECEIPT_PROCESS_FEE',
    RECEIVING_CHARGE_BY_QUANTITY = 'RECEIVING_CHARGE_BY_QUANTITY',
    RECEIVING_CHARGE_BY_VOLUME = 'RECEIVING_CHARGE_BY_VOLUME',
    ORDER_LINE_PROCESS_FEE = 'ORDER_LINE_PROCESS_FEE',
    ORDER_PROCESS_FEE = 'ORDER_PROCESS_FEE',
    SHIPPING_CHARGE_BY_QUANTITY = 'SHIPPING_CHARGE_BY_QUANTITY',
    SHIPPING_CHARGE_BY_VOLUME = 'SHIPPING_CHARGE_BY_VOLUME',
    OTHERS = 'OTHERS'
     * 
     */
}
