export enum PrintPageSize {
  A4 = 'A4',
  Letter = 'Letter',
  LetterSmall = 'LetterSmall',
  Tabloid = 'Tabloid',
  Ledger = 'Ledger',
  Legal = 'Legal',
  Statement = 'Statement',
  Executive = 'Executive',
  A3 = 'A3',
  A4Small = 'A4Small',
  A5 = 'A5',
  B4 = 'B4',
  B5 = 'B5',
  Folio = 'Folio',
  Quarto = 'Quarto',
  qr10X14 = 'qr10X14',
  qr11X17 = 'qr11X17',
  Note = 'Note',
  Env9 = 'Env9',
  Env10 = 'Env10',
  Env11 = 'Env11',
  Env12 = 'Env12',
  Env14 = 'Env14',
  Sheet = 'Sheet',
  DSheet = 'DSheet',
  ESheet = 'ESheet',
  
}
