export enum TrailerStatus {
    CANCELLED = 'CANCELLED',
    PENDING = 'PENDING',
    INPROCESS = 'INPROCESS',
    LOADING_IN_PROCESS = 'LOADING_IN_PROCESS',
    LOADED = 'LOADED',
    DISPATCHED = 'DISPATCHED'
}
