export enum AlertType {
    
    INTEGRATION_FAIL = "INTEGRATION_FAIL",
    INTEGRATION_SUCCESS = "INTEGRATION_SUCCESS",
    ORDER_COMPLETE = "ORDER_COMPLETE",
    INVENTORY_STATUS_CHANGE = "INVENTORY_STATUS_CHANGE",
    INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT",
    RECEIPT_COMPLETE = "RECEIPT_COMPLETE",
    INTEGRATION_TO_HOST_SUCCESS = "INTEGRATION_TO_HOST_SUCCESS",
    INTEGRATION_TO_HOST_FAIL = "INTEGRATION_TO_HOST_FAIL",
}
