export enum QcInspectionRequestType {
    BY_INVENTORY="BY_INVENTORY",
    BY_ITEM="BY_ITEM",
    BY_WORK_ORDER_SAMPLING="BY_WORK_ORDER_SAMPLING",
    INBOUND_BY_INVENTORY="INBOUND_BY_INVENTORY",
    MANUAL_BY_INVENTORY="MANUAL_BY_INVENTORY",
}
