export enum WorkTaskType {
    INVENTORY_MOVEMENT = 'INVENTORY_MOVEMENT',
    INVENTORY_MOVEMENT_CROSS_WAREHOUSE_OUT = 'INVENTORY_MOVEMENT_CROSS_WAREHOUSE_OUT',
    INVENTORY_MOVEMENT_CROSS_WAREHOUSE_IN = 'INVENTORY_MOVEMENT_CROSS_WAREHOUSE_IN',
    PICK = 'PICK',
    PUT_AWAY = 'PUT_AWAY',
    BULK_PICK = 'BULK_PICK',
    LIST_PICK = 'LIST_PICK'
}
