export enum ListPickGroupRuleType {
  BY_ORDER = 'BY_ORDER',
  BY_SHIPMENT = 'BY_SHIPMENT',
  BY_CARRIER = 'BY_CARRIER',
  BY_CUSTOMER = 'BY_CUSTOMER',
  BY_LOCATION_GROUP = 'BY_LOCATION_GROUP', 
  BY_STOP = 'BY_STOP',
  BY_TRAILER_APPOINTMENT = 'BY_TRAILER_APPOINTMENT',
  BY_ITEM = 'BY_ITEM',
  BY_WAVE = 'BY_WAVE',
  BY_PICK_ZONE = 'BY_PICK_ZONE',
}
