export enum OrderActivityType {
    
    ORDER_PLAN = 'ORDER_PLAN',
    ORDER_ALLOCATION = 'ORDER_ALLOCATION',
    PICK_CALCELLATION = 'PICK_CALCELLATION',
    SHIPMENT_LINE_CANCELLATION = 'SHIPMENT_LINE_CANCELLATION',
    SHIPMENT_CANCELLATION = 'SHIPMENT_CANCELLATION',
    SHIPMENT_STAGE = 'SHIPMENT_STAGE',
    SHIPMENT_LOADING = 'SHIPMENT_LOADING',
    SHIPMENT_DISPATCH = 'SHIPMENT_DISPATCH',
    ORDER_COMPLETE = 'ORDER_COMPLETE',
    SHIPMENT_ALLOCATION = 'SHIPMENT_ALLOCATION',
    ORDER_CANCELLATION = 'ORDER_CANCELLATION',
    PICK_CONFIRM = 'PICK_CONFIRM',
    SHORT_ALLOCATION_CANCELLATION = 'SHORT_ALLOCATION_CANCELLATION',
    SHORT_ALLOCATION_ALLOCATE = 'SHORT_ALLOCATION_ALLOCATE',
    ORDER_CREATE = 'ORDER_CREATE'
}
