export enum InventoryActivityType {
  INVENTORY_MOVEMENT = "INVENTORY_MOVEMENT",
  RECEIVING = "RECEIVING",
  REVERSE_RECEIVING = "REVERSE_RECEIVING",
  PICKING = "PICKING",
  UNPICKING = "UNPICKING",
  COUNT = "COUNT",
  CYCLE_COUNT = "CYCLE_COUNT",
  AUDIT_COUNT = "AUDIT_COUNT",
  INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT",
  INVENTORY_CONSOLIDATION = "INVENTORY_CONSOLIDATION",
  INVENTORY_SPLIT = "INVENTORY_SPLIT",
  RELABEL_LPN = "RELABEL_LPN",
  INVENTORY_STATUS_CHANGE = "INVENTORY_STATUS_CHANGE",
  INVENTORY_PACKAGE_TYPE_CHANGE = "INVENTORY_PACKAGE_TYPE_CHANGE",
  REVERSE_PRODUCTION = "REVERSE_PRODUCTION",
  REVERSE_BY_PRODUCT = "REVERSE_BY_PRODUCT"
}
