export enum InventoryActivityType {
  INVENTORY_MOVEMENT,
  RECEIVING,
  REVERSE_RECEIVING,
  PICKING,
  UNPICKING,
  COUNT,
  CYCLE_COUNT,
  AUDIT_COUNT,
  INVENTORY_ADJUSTMENT,
  INVENTORY_CONSOLIDATION,
  INVENTORY_SPLIT,
  RELABEL_LPN,
  INVENTORY_STATUS_CHANGE,
  INVENTORY_PACKAGE_TYPE_CHANGE,
  REVERSE_PRODUCTION,
  REVERSE_BY_PRODUCT
}
