import { Company } from "../../warehouse-layout/models/company";
import { Warehouse } from "../../warehouse-layout/models/warehouse";
import { ItemDefaultPackageUOM } from "./item-default-package-UOM";


export interface InventoryConfiguration {
    id?: number;

    companyId: number;

    company?: Company;

    warehouseId: number;
    warehouse?: Warehouse;

    lpnValidationRule: string;

    newItemAutoGenerateDefaultPackageType: boolean;

    newItemDefaultPackageTypeName: string;
    newItemDefaultPackageTypeDescription: string; 
    
    itemDefaultPackageUOMS: ItemDefaultPackageUOM[];

    inventoryAttribute1DisplayName?: string;
    inventoryAttribute1Enabled?: boolean;
    inventoryAttribute2DisplayName?: string;
    inventoryAttribute2Enabled?: boolean;
    inventoryAttribute3DisplayName?: string;
    inventoryAttribute3Enabled?: boolean;
    inventoryAttribute4DisplayName?: string;
    inventoryAttribute4Enabled?: boolean;
    inventoryAttribute5DisplayName?: string;
    inventoryAttribute5Enabled?: boolean;

}
