import { Company } from "../../warehouse-layout/models/company";
import { Warehouse } from "../../warehouse-layout/models/warehouse";
import { ItemDefaultPackageUOM } from "./item-default-package-UOM";


export interface InventoryConfiguration {
    id?: number;

    companyId: number;

    company?: Company;

    warehouseId: number;
    warehouse?: Warehouse;

    lpnValidationRule: string;

    newItemAutoGenerateDefaultPackageType: boolean;

    newItemDefaultPackageTypeName: string;
    newItemDefaultPackageTypeDescription: string; 
    
    itemDefaultPackageUOMS: ItemDefaultPackageUOM[];

}
