export enum WorkOrderStatus {
  CANCELLED = 'CANCELLED',
  PENDING = 'PENDING',
  INPROCESS = 'INPROCESS',
  STAGED = 'STAGED',
  WORK_IN_PROCESS = 'WORK_IN_PROCESS',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
}
