export enum CustomReportExecutionStatus {
  INIT = 'INIT',
  RUNNING = 'RUNNING',
  EXPORT_RESULT = 'EXPORT_RESULT',
  COMPLETE = 'COMPLETE',
  FAIL = 'FAIL',
  EXPIRED = 'EXPIRED',
  DOWNLOADING = 'DOWNLOADING',
}
