export enum ReportType {


    ORDER_PICK_SHEET = 'ORDER_PICK_SHEET',
    RECEIVING_DOCUMENT = 'RECEIVING_DOCUMENT',
    PUTAWAY_DOCUMENT = 'PUTAWAY_DOCUMENT',
    PICK_LIST_SHEET = 'PICK_LIST_SHEET',
    DELIVERY_NOTE = 'DELIVERY_NOTE',
    PACKING_SLIP = 'PACKING_SLIP',
    CYCLE_COUNT_SHEET = 'CYCLE_COUNT_SHEET',
    AUDIT_COUNT_SHEET = 'AUDIT_COUNT_SHEET',
    LPN_REPORT = 'LPN_REPORT',
    WORK_ORDER_PICK_SHEET = 'WORK_ORDER_PICK_SHEET',
    PRODUCTION_LINE_ASSIGNMENT_REPORT = 'PRODUCTION_LINE_ASSIGNMENT_REPORT',
    BILL_OF_LADING = 'BILL_OF_LADING',
    LPN_LABEL = 'LPN_LABEL',
    PRODUCTION_LINE_ASSIGNMENT_LABEL = 'PRODUCTION_LINE_ASSIGNMENT_LABEL',
    RECEIVING_LPN_LABEL = 'RECEIVING_LPN_LABEL',
    QC_INSPECTION_REQUEST_REPORT = 'QC_INSPECTION_REQUEST_REPORT',
    RECEIVING_LPN_REPORT = 'RECEIVING_LPN_REPORT',
}
