export enum ReportType {
 
    
 ORDER_PICK_SHEET = 'ORDER_PICK_SHEET',
 RECEIVING_DOCUMENT = 'RECEIVING_DOCUMENT',
 PUTAWAY_DOCUMENT = 'PUTAWAY_DOCUMENT',
 PICK_LIST_SHEET = 'PICK_LIST_SHEET',
 DELIVERY_NOTE = 'DELIVERY_NOTE',
 PACKING_SLIP = 'PACKING_SLIP',
 CYCLE_COUNT_SHEET = 'CYCLE_COUNT_SHEET',
 AUDIT_COUNT_SHEET = 'AUDIT_COUNT_SHEET',
}
